backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: recipe
    label: Recipe
    category: "test"
    folder: "src/pages"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { name: summary, label: Summary, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: tag, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
      - { name: path, label: Path, widget: string }
