backend:
  name: test-repo

media_folder: static/assets
public_folder: /assets

collections:
  - name: recipe
    label: Recipe
    category: "test"
    folder: "src/pages"
    path: '/{{slug}}/index'
    create: true
    fields:
      - { name: summary, label: Title, widget: string }
      - { name: tag, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
